# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWFhMGJiYTlkZDBjMjZhMjJhNWUyNTY3NWRhNWQ2MDM5N2Q1ODI2NzcyNjNmYWRmNjlhNWYxMjA5ZWUxZTZlYjMzYzI2YzNkZjY0ZTYzMmIxN2E1NmIzNjgxZjU0MDdiNTVjNzVlZGY2ZGJjNTA3YWI5NTlmZDZkNjg5YzIzZDM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
